### ISSUE TITLE
ARM Subscriptions don't show up in list

### ISSUE THREAD

**Issue by Yliche** [Duber/AzureReleaseSwapTask#1]
I only see classic subscriptions showing up in my available drop down menu. No ARM subscriptions show up.

**Comment by Duber** [comment]
Thanks for the feedback @Yliche , I will look into it and tell you something soon !

**Comment by naeemsarfraz** [comment]
Hey @Duber, I don't mind adding this as I need this for my pipeline.

I think it's best added as a new task? So your extension ends up with two tasks, the new one being called "AzureRM Web App Swap". What do you think?

**Comment by naeemsarfraz** [comment]
Just submitted a PR for this #2 

I didn't create a second task but just modified the existing one so that you can alternate between ARM and Classic.

**Comment by Duber** [comment]
Hello @naeemsarfraz, first of all let me thank you for your time and work :)

Regarding the pull request, we should consider if we really need this anymore since Microsoft released its own ARM Swap task a month ago.

Check it out:

![image](https://cloud.githubusercontent.com/assets/999284/20539425/387c6020-b0f5-11e6-981a-f78d1143d5a6.png)
![image](https://cloud.githubusercontent.com/assets/999284/20539455/5cbbfffe-b0f5-11e6-91ae-110da6d86106.png)

Also, I'm worried that updating the extension with this feature will break existing installations because of the new inputs of the task. For this reason I think that creating a second task as you first proposed might be a better approach.

What do you think ?

**Comment by naeemsarfraz** [comment]
@Duber I missed the fact there is a new task that covers this.

In that case I think it's best to leave this PR. If people want to swap slots for RM sites then they should go and use the new task.
